### ISSUE TITLE
Defined character set

### ISSUE THREAD

**Issue by vilberger** [YOURLS/random-keywords#1]
Hello,

you wrote: plugin now complies to character set defined in config.php.
Could you please let me know which variable has to be defined?
Can you give an example please?
thank you, n brgds
Dom

**Comment by ozh** [comment]
The charset is defined by constant `YOURLS_URL_CONVERT` or modified with a plugin, see for instance the core plugin `hyphens-in-urls`

**Comment by vilberger** [comment]
right, but ...
/*
- 36: generates all lowercase keywords (ie: 13jkm)
- 62: generates mixed case keywords (ie: 13jKm or 13JKm)
- Stick to one setting. It's best not to change after you've started creating links.
  */

I cannot define there that e.g. 0 and O (sero and letter o), or 1 and I  should not be used ...

**Comment by ozh** [comment]
As I've said above, the charset can be modified with a plugin
