### ISSUE TITLE
If there are no available keywords, the plugin fails to generate a url

### ISSUE THREAD

**Issue by chromaniac2** [YOURLS/random-keywords#5]
I am guessing this is by design? I set it at 1 and it stopped generating keywords after it exhausted all available options (i assume)? I thought it would automatically switch to 2 alphabets once it runs out of single character urls. Just wanted to check. I do understand that this option is designed for a higher setting... I have now set it to 2 and would wait for it to exhaust all remaining keywords before I move to 3 manually.

**Comment by ozh** [comment]
Expected behavior indeed

**Comment by chromaniac2** [comment]
Right. Would be nice if the plugin can at least show an error if there are no available keywords? In my case, the button just kept on showing the loader. Thanks!

**Comment by ozh** [comment]
Seems complicated to do. How would the plugin know that there are no available keywords?

**Comment by chromaniac2** [comment]
True. Maybe a timeout setting. If the plugin cannot find an available keyword within x seconds, just show an error? Personally, I would prefer an option that tells it to generate a random keyword with an additional alphabet which is what YOURLS does when it runs out of sequential keywords without the plugin. Thanks!
