### ISSUE TITLE
Option for using hyphens in keyword with 'Allow Hyphens in Short URLs'

### ISSUE THREAD

**Issue by atdr** [YOURLS/random-keywords#8]
When using core plugin **Allow Hyphens in Short URLs** hyphens are included in the random keywords.

An option to generate random keywords *without* hyphens whilst preserving the ability to use them in manually-entered keywords would be useful (like Bitly).

---
PS: Not sure if this is best filed here or in YOURLS/YOURLS as an issue for the hyphens plugin. Please delete/move as necessary

**Comment by ozh** [comment]
Indeed, that's unfortunate. I think plugin **Allow Hyphens in Short URLs** should take care of that and make sure random keywords are hyphen free. I'll look into this.
