### ISSUE TITLE
collision handling

### ISSUE THREAD

**Issue by tessus** [YOURLS/random-keywords#9]
I was looking at the code and failed to see how collisions are handled. What heppens, if the generated keyword already exists. I admit, the chances are pretty low, but still, there doesn't seem to be a test that would handle such a case.

**Comment by ozh** [comment]
This code is [in YOURLS](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L276-L277) because it's not plugin dependent (other plugin can rely on it, it also simply runs everytime a sequential keyword is generated)
